//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _445_project
{
    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.Button btnLogIn;
        protected global::System.Web.UI.WebControls.Button btnStaffLogIn;
        protected global::System.Web.UI.WebControls.Label lblActiveUsers;

        protected global::System.Web.UI.WebControls.TextBox passwordInputTextBox;
        protected global::System.Web.UI.WebControls.Label lblEncrypted;
        protected global::System.Web.UI.WebControls.Label lblVerifyResult;

        protected global::System.Web.UI.WebControls.TextBox InputTextBox;
        protected global::System.Web.UI.WebControls.TextBox findTextBox;
        protected global::System.Web.UI.WebControls.TextBox ReplaceTextBox;
        protected global::System.Web.UI.WebControls.Label lblWebServiceResult;

        protected global::System.Web.UI.WebControls.TextBox url_tb;
        protected global::System.Web.UI.WebControls.Button getContents_bt;
        protected global::System.Web.UI.WebControls.TextBox fullWebData_tb;

        protected global::System.Web.UI.WebControls.TextBox occurencesInput_tb;
        protected global::System.Web.UI.WebControls.Button getJson_bt;
        protected global::System.Web.UI.WebControls.TextBox json_tb;

        protected global::System.Web.UI.WebControls.TextBox unfilteredText_tb;
        protected global::System.Web.UI.WebControls.Button filter_bt;
        protected global::System.Web.UI.WebControls.TextBox filteredText_tb;

        /* -------- NEW CONTROLS -------- */
        protected global::System.Web.UI.WebControls.TextBox hashInput_tb;
        protected global::System.Web.UI.WebControls.Button btnHash;
        protected global::System.Web.UI.WebControls.Label lblHash;

        protected global::System.Web.UI.WebControls.TextBox reverseInput_tb;
        protected global::System.Web.UI.WebControls.Button btnReverse;
        protected global::System.Web.UI.WebControls.Label lblReverseResult;

        protected global::System.Web.UI.WebControls.TextBox wordCountInput_tb;
        protected global::System.Web.UI.WebControls.Button btnWordCount;
        protected global::System.Web.UI.WebControls.Label lblWordCount;
    }
}
